### ISSUE TITLE
How to use the virtual machine bash?

### ISSUE THREAD

**Issue by Finesse** [abyss-soft/webdev#1]
Hello. I'm new to Vagrant so please excuse me if my question is stupid.

I want to connect to the shell of the virtual machine launched by Vagrant to run some commands and change some settings. I've opened the login prompt of the virtual machine (in the Virtual Box interface) but I don't know the login and the password and I cant find them in the repository. How can I connect to the virtual machine command shell directly or through SSH?

**Comment by abyss-soft** [comment]
Good day!
Since we use Vagrant, we use standard Vagrant passwords for access:
username: vagrant
password: vagrant


------------Alex
-------- Исходное сообщение --------От: Surgie Finesse <notifications@github.com> Дата: 07.01.2019  14:14  (GMT+10:00) Кому: abyss-soft/webdev <webdev@noreply.github.com> Копия: Subscribed <subscribed@noreply.github.com> Тема: [abyss-soft/webdev] How to use the virtual machine bash? (#1) 
Hello. I'm new to Vagrant so please excuse me if my question is stupid.
I want to connect to the shell of the virtual machine launched by Vagrant to run some commands and change some settings. I've opened the login prompt of the virtual machine (in the Virtual Box interface) but I don't know the login and the password and I cant find them in the repository. How can I connect to the virtual machine command shell directly or through SSH?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/abyss-soft/webdev","title":"abyss-soft/webdev","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/abyss-soft/webdev"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"How to use the virtual machine bash? (#1)"}],"action":{"name":"View Issue","url":"https://github.com/abyss-soft/webdev/issues/1"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/abyss-soft/webdev/issues/1",
"url": "https://github.com/abyss-soft/webdev/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Finesse** [comment]
Thank you!
